FROM ubuntu

RUN apt update && apt -y upgrade && apt install -y git dotnet-sdk-6.0
RUN git clone https://github.com/szymongamza/InventoryUniversity.git
WORKDIR /InventoryUniversity
RUN dotnet restore ./InventoryUniversity.sln
RUN dotnet build ./InventoryUniversity.sln